INSERT INTO Department(Code, Name) VALUES('CSE', 'Computer Science & Engineering')
INSERT INTO Department(Code, Name) VALUES('ME', 'Mechanical Engineering')
INSERT INTO Department(Code, Name) VALUES('EEE', 'Electronics & Electrical Engineering')
INSERT INTO Department(Code, Name) VALUES('CE', 'Civil Engineering')
INSERT INTO Department(Code, Name) VALUES('TE', 'Textile Engineering')

INSERT INTO Semester(Code, Name) VALUES('SEM-1', '1ST SEMESTER')
INSERT INTO Semester(Code, Name) VALUES('SEM-2', '2ND SEMESTER')
INSERT INTO Semester(Code, Name) VALUES('SEM-3', '3RD SEMESTER')
INSERT INTO Semester(Code, Name) VALUES('SEM-4', '4TH SEMESTER')
INSERT INTO Semester(Code, Name) VALUES('SEM-5', '5TH SEMESTER')
INSERT INTO Semester(Code, Name) VALUES('SEM-6', '6TH SEMESTER')
INSERT INTO Semester(Code, Name) VALUES('SEM-7', '7TH SEMESTER')
INSERT INTO Semester(Code, Name) VALUES('SEM-8', '8TH SEMESTER')

INSERT INTO Designation(Code, Name) VALUES('AP', 'Assistant Professor')
INSERT INTO Designation(Code, Name) VALUES('AS', 'Assocaiate Professor')
INSERT INTO Designation(Code, Name) VALUES('LE', 'Lecturer')

INSERT INTO Room(Code, Name) VALUES('A-201', 'A-201')
INSERT INTO Room(Code, Name) VALUES('A-202', 'A-202')
INSERT INTO Room(Code, Name) VALUES('A-203', 'A-203')
INSERT INTO Room(Code, Name) VALUES('B-201', 'B-201')
INSERT INTO Room(Code, Name) VALUES('B-202', 'B-202')
INSERT INTO Room(Code, Name) VALUES('B-203', 'B-203')
INSERT INTO Room(Code, Name) VALUES('A-301', 'A-301')
INSERT INTO Room(Code, Name) VALUES('A-302', 'A-302')
INSERT INTO Room(Code, Name) VALUES('B-301', 'B-301')
INSERT INTO Room(Code, Name) VALUES('B-302', 'B-302')

